### ISSUE TITLE
Exit early if errors are encountered

### ISSUE THREAD

**Issue by ScopeyNZ** [chec/seeder#8]
Currently an error will show in console (like 401 Unauthorized) but it will continue with seeding. This can be a problem when assets are seeding - as it refers to past seeded items. You can just get an error "undefined index" in this case which looks pretty average.

We should just cancel with failed seeding if there's an error.

**Comment by sccalabr** [comment]
Id like to give this a try. Where should I start looking at?

**Comment by ScopeyNZ** [comment]
The whole library is pretty much just the `index.js` file. We already catch errors here: https://github.com/chec/seeder/blob/master/index.js#L72. We use the `promise-queue` library though, so we'll need to cancel the full queue of promises. And then we'll probably want a message that's pretty clear what happened. 

I'd be happy with a PR that went that far, but I think eventually it'd be nice if we tried to clean up resources we added too (ie. delete any we added).

**Comment by sccalabr** [comment]
So something like a boolean in the catch that signifies an error has occurred. If error has occurred set the queuedPromises to an empty array

**Comment by ScopeyNZ** [comment]
Hmmn. I'm not convinced that will work. The way this works is that it will actually queue up all the fetches as promises, and puts them all the queuedPromises array, but setting that variable to null probably won't prevent them from running. They still exist in the application, you've just removed your reference to them.

I'm not actually quite sure on a good approach for this right now. I think it will probably involve removing `promise-queue` - we don't actually use it for concurrency (which is why we added it), so this task will actually involve a bit of a refactor.

**Comment by Tomburgs** [comment]
@ScopeyNZ I think we can close this issue?
